### ISSUE TITLE
speech log

### ISSUE THREAD

**Issue by scoy028** [1901cs-maries-roc/julia#51]
so a user knows a history of speech; speech confirmation

**Comment by CelineChole** [comment]
Annyang callback functions

annyang.addCallback('resultMatch', function(userSaid, commandText, phrases) {
  console.log(userSaid); // sample output: 'hello'
  console.log(commandText); // sample output: 'hello (there)'
  console.log(phrases); // sample output: ['hello', 'halo', 'yellow', 'polo', 'hello kitty']
});
